import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'
import CardV from '../components/CardV'
import pav from '../images/Pav1.jpg'
import pav3 from '../images/pav3.png'
import pav2 from '../images/pav2.png'
import pav4 from '../images/pav4.png'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Swadesh App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div class="bg-emerald w-screen absolute -mt-96 h-96 flex overflow-hidden">
                <div class="flex">
                    <svg
                        class="m-20"
                        width="37"
                        height="48"
                        viewBox="0 0 37 48"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M30.5406 18.4271C26.9698 14.8552 22.2256 12.8931 17.1795 12.8931H16.9111C17.0368 12.4741 17.104 12.0379 17.104 11.5853C17.104 9.0361 15.0252 6.95672 12.4769 6.95672H7.12908C6.76027 6.95672 6.41658 6.81419 6.15675 6.58777C6.09807 6.50395 6.03102 6.4201 5.95556 6.34464C5.93881 6.32785 5.91366 6.30271 5.88852 6.28593C5.73762 6.05115 5.64543 5.77445 5.64543 5.47261C5.64543 4.65087 6.30761 3.98847 7.12908 3.98847H12.1752C13.0973 3.98847 13.8516 3.23383 13.8516 2.31151C13.8516 1.38916 13.0973 0.634521 12.1752 0.634521H7.12908C4.46352 0.634521 2.29253 2.8062 2.29253 5.47261C2.29253 6.10986 2.41828 6.72194 2.64458 7.28374L0.490363 9.44689C-0.163454 10.1009 -0.163454 11.166 0.490363 11.8201C0.817271 12.1469 1.24476 12.3148 1.67225 12.3148C2.09973 12.3148 2.52725 12.1469 2.85416 11.8201L4.90779 9.75737C5.57 10.1009 6.33279 10.3024 7.12908 10.3024H12.4769C13.1811 10.3024 13.751 10.8725 13.751 11.5768C13.751 12.2811 13.1811 12.8513 12.4769 12.8513H9.36715C5.24309 12.8513 1.89018 16.2053 1.89018 20.3307C1.89018 24.4558 5.24309 27.8099 9.36715 27.8099H15.3185C17.9841 27.8099 20.1468 29.9732 20.1468 32.6396V39.2048C20.1468 40.1272 20.9012 40.8819 21.823 40.8819C22.7452 40.8819 23.4995 40.1272 23.4995 39.2048V32.6481C23.4995 28.1368 19.8281 24.4643 15.3185 24.4643H9.36715C7.09555 24.4643 5.24309 22.6112 5.24309 20.3389C5.24309 18.2344 6.82732 16.4904 8.8642 16.2387C8.87259 16.2387 8.88098 16.2387 8.88098 16.2387H17.1795C25.7462 16.2387 32.72 23.215 32.72 31.7844V46.0721C32.72 46.9945 33.4746 47.7491 34.3965 47.7491C35.3186 47.7491 36.073 46.9945 36.073 46.0721V31.7844C36.073 26.7366 34.1114 21.9908 30.5406 18.4271Z"
                            fill="#CB912C"
                        />
                    </svg>
                    <p class="mt-20 -ml-14 text-white text-xl font-extrabold">Swadesh</p>
                </div>
                <p class="mt-36  font-bold text-3xl lg:-ml-8 -ml-24 text-white text-xl">
                    All Properties
                </p>
                <svg
                    class=" absolute mt-40"
                    overflow="hidden"
                    width="230"
                    height="491"
                    viewBox="0 0 330 871"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <circle cx="-15.5" cy="245.5" r="245" stroke="#CB912C" />
                </svg>
                <svg
                    class=" absolute mt-40"
                    width="270"
                    height="491"
                    viewBox="0 0 420 791"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <circle cx="24.5" cy="245.5" r="245" stroke="#06433C" />
                </svg>
            </div>

            <div class="mt-80 lg:mt-96 w-3/4 space-y-96 object-center absolute -top-36 overflow-y-visible">
                <Card />
            </div>
            <div class=" t-60  -ml:80">
                <p class="text-left gray absolute lg:-ml-96 -ml-40  top-60 lg:top-40 font-bold leading-8 text-3xl">
                    Past properties
                </p>
            </div>
            <div class="flex flex-col md:flex-row justify-evenly m-12 mt-96 absolute top-32 lg:inset-y-80 sm:inset-y-72">
                <CardV
                    image={pav2}
                    name="The Pavilion III"
                    loc="Outer Ring Road, Bangalore"
                    area="52,277"
                    Price="$12,338"
                    yield="9.14%"
                    target="18.1"
                    funding="63%"
                />
                <CardV
                    image={pav3}
                    name="The Pavilion III"
                    loc="Outer Ring Road, Bangalore"
                    area="52,277"
                    Price="$12,338"
                    yield="9.14%"
                    target="18.1%"
                    funding="63%"
                />
                <CardV
                    image={pav4}
                    name="The Pavilion III"
                    loc="Outer Ring Road, Bangalore"
                    area="52,277"
                    Price="$12,338"
                    yield="9.14%"
                    target="18.1%"
                    funding="63%"
                />
            </div>

            <div class="flex flex-col md:flex-row justify-evenly m-12 -mt-24 lg:mt-80 absolute inset-y-108 lg:inset-y-64 b-20">
                <CardV
                    image={pav3}
                    name="The Pavilion III"
                    loc="Outer Ring Road, Bangalore"
                    area="52,277"
                    Price="$12,338"
                    yield="9.14%"
                    target="18.1%"
                    funding="63%"
                />
                <CardV
                    image={pav2}
                    name="The Pavilion III"
                    loc="Outer Ring Road, Bangalore"
                    area="52,277"
                    Price="$12,338"
                    yield="9.14%"
                    target="18.1%"
                    funding="63%"
                />
                <CardV
                    image={pav4}
                    name="The Pavilion III"
                    loc="Outer Ring Road, Bangalore"
                    area="52,277"
                    Price="$12,338"
                    yield="9.14%"
                    target="18.1%"
                    funding="63%"
                />
            </div>
        </div>
    )
}
